#!/usr/bin/env bash

IFS= read -rd '' dirname < <(dirname -z -- "$0")
cd -- "$dirname"/.. || exit "$?"

shopt -s nullglob
for testfile in tests/test_*.py; do
    python3 -m unittest "$testfile" || exit "$?"
done
